borrowing:
  time: 20
  prolongation: 10
spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3388/library?createDatabaseIfNotExist=true&useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC&autoReconnect=true
    username: root
    password: 1234
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
    show-sql: on
  jackson:
    date-format: yyyy-MM-dd
#    docker run --name librarydb -e MYSQL_ROOT_PASSWORD=1234 -e MYSQL_DATABASE=library -d -p 3388:3306 mysql:latest

